import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { Navbar } from "~/components/navbar";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Squeeze | LLM Token Optimizer",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable} dark`} lang="en">
			<body>
				<TRPCReactProvider>
					<Navbar />
					{children}
				</TRPCReactProvider>
			</body>
		</html>
	);
}
